### PR TITLE
Fixes run.py & Adds .gitignore

### PR DESCRIPTION
**Pull request by gabru-md**
Review : @dynamitechetan @ParthS007 

Cheers!

### CODE REVIEW

**Comment by dynamitechetan** [comment]
set hai sab.. bas gitignore wali file alag pr me aa gyi hai vo hat de

**Comment by gabru-md** [comment]
Done!

**Comment by dynamitechetan** [comment]
kaha pe?

**Comment by xeon-zolt** [comment]
@dynamitechetan app api wala

**Pull request merged**
