### PR TITLE
Adds Token to db

### PR DESCRIPTION
**Pull request by gabru-md**
CC : @dynamitechetan @xeon-zolt @ParthS007 

please see if the implementation is correct.
Thanks :)

### CODE REVIEW

**Comment by dynamitechetan** [comment]
ek saval tha .. ye tokens api call me kaam aayenge ?? kuch jwt ki tarah?

**Comment by gabru-md** [comment]
Yes.
Like when we create some type of wrapper then the wraper will be initialised with this token. And this token will then be used for authenticating the incoming requests

**Comment by dynamitechetan** [comment]
better way ho skta hai iska thoda.. python me jwt ki kaafi libraries hain to bas fir ek decorator lagana hoga or us poori api pe auth chal padegi .. abhi ke liye ye theek hai.

**Comment by gabru-md** [comment]
Okay, so in that case should you merge or close?

**Pull request merged**
